apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: fix-resolv
  name: fix-resolv
  namespace: fix-resolv
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fix-resolv
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fix-resolv
    spec:
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SEARCH
          value: mauilion.com
        image: quay.io/dcooley/fixresolvconf:0.1
        imagePullPolicy: Always
        name: fix-resolv
        volumeMounts:
        - mountPath: /mnt/etc
          name: node-etc
      dnsPolicy: Default
      nodeSelector:
        node-role.kubernetes.io/node: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: fix-resolv
      serviceAccountName: fix-resolv
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - hostPath:
          path: /etc/
          type: ""
        name: node-etc
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
